# Generated by Django 5.0.6 on 2024-05-29 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('[+-/%\\s]', inverse_match=True, message='username cant have special caracter')])),
                ('first_name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^(?!.*[a-z][A-Z])(?!.*[A-Z][a-z]+[A-Z]).*')])),
                ('last_name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^(?!.*[a-z][A-Z])(?!.*[A-Z][a-z]+[A-Z]).*')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('postal', models.CharField(max_length=4)),
                ('url_img', models.CharField(max_length=255)),
            ],
        ),
    ]
